### ISSUE TITLE
Executing `make train` does not work

### ISSUE THREAD

**Issue by caokaifa** [upkie/ppo_balancer#3]
Hi, the project is good work, But I start the work, it is fault as follows:

```
xception ignored in: <function UpkieBaseEnv.__del__ at 0x7fe4fde1f420>
Traceback (most recent call last):
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/site-packages/upkie/envs/upkie_base_env.py", line 110, in __del__
    self.close()
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/site-packages/upkie/envs/upkie_base_env.py", line 116, in close
    self._spine.stop()
    ^^^^^^^^^^^
AttributeError: 'UpkieGroundVelocity' object has no attribute '_spine'
Process ForkProcess-2:
Exception ignored in: <function UpkieBaseEnv.__del__ at 0x7fe4fde1f420>
Traceback (most recent call last):
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/site-packages/upkie/envs/upkie_base_env.py", line 110, in __del__
    self.close()
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/site-packages/upkie/envs/upkie_base_env.py", line 116, in close
Traceback (most recent call last):
    self._spine.stop()
    ^^^^^^^^^^^
AttributeError: 'UpkieGroundVelocity' object has no attribute '_spine'
Process ForkProcess-1:
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UpkieGroundVelocity.__init__() got an unexpected keyword argument 'reward_weights'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/smart/.cache/bazel/_bazel_smart/89047edaaeab6b933ce9d39a9810701f/execroot/ppo_balancer/bazel-out/k8-opt/bin/ppo_balancer/train.runfiles/ppo_balancer/ppo_balancer/train.py", line 179, in _init
    velocity_env = gymnasium.make(
                   ^^^^^^^^^^^^^^^
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/site-packages/gymnasium/envs/registration.py", line 814, in make
    raise type(e)(
TypeError: UpkieGroundVelocity.__init__() got an unexpected keyword argument 'reward_weights' was raised from the environment creator for UpkieGroundVelocity-v3 with kwargs ({'frequency': 200, 'regulate_frequency': False, 'reward_weights': <upkie.envs.rewards.wheeled_inverted_pendulum_reward.WheeledInvertedPendulumReward object at 0x7fe4fb2b1250>, 'shm_name': '/slept', 'spine_config': {'bullet': {'torque_control': {'kd': 1.0}}}, 'max_ground_velocity': 1.0})
Traceback (most recent call last):
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UpkieGroundVelocity.__init__() got an unexpected keyword argument 'reward_weights'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/smart/.cache/bazel/_bazel_smart/89047edaaeab6b933ce9d39a9810701f/execroot/ppo_balancer/bazel-out/k8-opt/bin/ppo_balancer/train.runfiles/ppo_balancer/ppo_balancer/train.py", line 179, in _init
    velocity_env = gymnasium.make(
                   ^^^^^^^^^^^^^^^
  File "/home/smart/anaconda3/envs/ppo_balancer/lib/python3.12/site-packages/gymnasium/envs/registration.py", line 814, in make
    raise type(e)(
TypeError: UpkieGroundVelocity.__init__() got an unexpected keyword argument 'reward_weights' was raised from the environment creator for UpkieGroundVelocity-v3 with kwargs ({'frequency': 200, 'regulate_frequency': False, 'reward_weights': <upkie.envs.rewards.wheeled_inverted_pendulum_reward.WheeledInvertedPendulumReward object at 0x7fe4fa52c110>, 'shm_name': '/plebeians', 'spine_config': {'bullet': {'torque_control': {'kd': 1.0}}}, 'max_ground_velocity': 1.0})
[2024-08-27 15:01:46.573] [info] Command line: shm_name = /slept
[2024-08-27 15:01:46.573] [info] Command line: nb_substeps = 5
[2024-08-27 15:01:46.573] [info] Command line: spine_frequency =
```

**Comment by stephane-caron** [comment]
Thank you for reporting this :+1: The error was due to https://github.com/upkie/ppo_balancer/pull/2 which hadn't been merged yet after the release of Upkie 5.1.0. It should be fixed now that the PR is merged.

You can try again by running from this repository:

```console
make clean
git pull
make train_and_show
```
